name: Deploy to FTP
on: push

jobs:
  deploy-to-prod:
    if: github.ref == 'refs/heads/main'
    name: Deploy production branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to FTP (Prod)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /
          dangerous-clean-slate: false
          exclude: |
            projekt/**
            admin/project_auth_data.php
            .git*
            .git*/**
            **/*.bat
            .vscode/**
